
use std::hash::Hash;
use std::str::FromStr;

use osm_parser_macros::FeatureSubType;
use osm_parser_macros::feature_sub_type;

use strum_macros::{
    EnumIter,
    EnumString,
    Display
};

use enum_dispatch::enum_dispatch;

#[enum_dispatch]
pub trait FeatureSubType {

    fn create(&self, attr: &str) -> Option<Feature>;
    fn subtype_to_string(&self) -> String;
}

#[feature_sub_type]
pub enum Advertising {
    Billboard,
    Board,
    Column,
    Flag,
    PosterBox,
    Screen,
    Sculpture,
    Sign,
    Tarp,
    Totem,
    WallPainting,
    Yes,
}

#[feature_sub_type]
pub enum Aerialway {
    CableCar,
    Gondola,
    MixedLift,
    ChairLift,
    DragLift,
    #[strum(serialize = "t-bar")]
    TBar,
    #[strum(serialize = "j-bar")]
    JBar,
    Platter,
    RopeTow,
    MagicCarpet,
    ZipLine,
    Goods,
    Pylon,
    Station
}

#[feature_sub_type]
pub enum Aeroway {
    Aerodome,
    Airstrip,
    Apron,
    ControlCenter,
    Fuel,
    Gate,
    Hangar,
    Helipad,
    Heliport,
    HighwayStrip,
    HoldingPosition,
    JetBridge,
    ModelRunway,
    Navigationaid,
    Beacon,
    ParkingPosition,
    Runway,
    Speceport,
    Stopway,
    Taxiline,
    Taxiway,
    Terminal,
    Tower,
    Windsock,

    FlameTranch,
    Landingpad,
    LaunchComplex,
    Launchpad,
    Spaceport,
}

#[feature_sub_type]
pub enum Amenity {
    // Sustenance
    Bar,
    Biergarten,
    Cafe,
    FastFood,
    FoodCourt,
    IceCream,
    Pub,
    Restaurant,
    // Education
    College,
    DancingSchool,
    DrivingSchool,
    FirstAidSchool,
    Kindergarten,
    LanguageSchool,
    Library,
    SurfSchool,
    ToyLibrary,
    ResearchInstitute,
    Training,
    MusicSchool,
    School,
    TrafficPark,
    University,
    // Transportation
    BicycleParking,
    BicycleRepairStation,
    BicycleRental,
    BicyleWash,
    BoatRental,
    BoatStorage,
    BoatSharing,
    BusStation,
    CarRental,
    CarSharing,
    CarWash,
    CompressedAir,
    VehicleInspection,
    ChargingStation,
    DriverTraining,
    FerryTerminal,
    Fuel,
    GritBin,
    MotorcycleParking,
    Parking,
    ParkingEntrance,
    ParkingSpace,
    Taxi,
    Weighbridge,
    // Financial
    Atm,
    PaymentTerminal,
    Bank,
    BureauDeChange,
    MoneyTransfer,
    PaymentCentre,
    // Healthcare
    BabyHatch,
    Clinic,
    Dentist,
    Doctors,
    Hospital,
    NursingHome,
    Pharmacy,
    SocialFacillity,
    Veterinary,
    // Entertainment, Arts & Culture
    ArtsCentre,
    Brothel,
    Casino,
    Cinema,
    CommunityCentre,
    ConferenceCentre,
    EventsVenue,
    ExhibitionCentre,
    Fountain,
    Gambling,
    HookahLounge,
    LoveHotel,
    MusicVenue,
    Nightclub,
    Planetarium,
    PublicBookcase,
    SocialCentre,
    Stage,
    Stripclub,
    Studio,
    Swingerclub,
    Theatre,
    // Public Service
    Courthouse,
    FireStation,
    Police,
    PostBox,
    PostDepot,
    PostOffice,
    Prison,
    RangerStation,
    Townhall,
    // Facilities
    Bbq,
    Bench,
    CheckIn,
    DogToilet,
    DressingRoom,
    DrinkingWater,
    GiveBox,
    Longue,
    Mailroom,
    ParcelLocker,
    Shelter,
    Shower,
    Telephone,
    Toilets,
    WaterPoint,
    WateringPlace,
    // Waste Management
    SanitaryDumpStation,
    Recycling,
    WasteBasket,
    WasteDisposal,
    WasteTransferStation,
    // Others
    AnimalBoarding,
    AnimalBreeding,
    AnimalShelter,
    AnimalTraining,
    BakingOven,
    Clock,
    Crematorium,
    DiveCentre,
    Dojo,
    FuneralHall,
    GraveYard,
    HuntingStand,
    InternetCafe,
    Kitchen,
    KneippWaterCure,
    Lounger,
    Marketplace,
    Mediation,
    Monastery,
    Mortuary,
    PhotoBooth,
    PlaceOfMourning,
    PlaceOfWorship,
    PublicBath,
    RefugeeSite,
    SocialFacility,
    VendingMachine,
    Hydrant
}

#[feature_sub_type]
pub enum Barrier {
    // Linear barriers (e.g., along a path or road)
    CableBarrier,
    CityWall,
    Ditch,
    GuardRail,
    Handrail,
    Hedge,
    RetainingWall,
    Wall,
    // Access control on highways (e.g., for blocking a path or road)
    Block,
    Bollard,
    BorderControl,
    BumpeGate,
    BusTrap,
    CattleGrid,
    Coupure,
    CycleBarrier,
    Debirs,
    Entrance,
    FloatingBoom,
    #[strum(serialize = "full-height_turnstile")]
    FullHeightTurnstile,
    Gate,
    HampshireGate,
    HeightRestrictor,
    HorseStile,
    KentCarriageGap,
    KissingGate,
    LiftGate,
    MotorcycleBarrier,
    Planter,
    SallyPort,
    SidingBeam,
    SidingGate,
    Spikes,
    Stile,
    SumpBuster,
    SwingGate,
    TollBooth,
    Tunstile,
    Wedge,
    WicketGate,
    ParkingLock,
    Yes,
    // Linear barriers or access control on highway (e.g., along or for blocking a path or road)
    Bar,
    BarrierBoard,
    Chain,
    Fence,
    JerseyBarrier,
    Kerb,
    Log,
    Rope,
    TankTrap,
    Tyres,
    DelineatorKerb,
    Armadillo
}

#[feature_sub_type]
pub enum Boundary {
    AboriginalLands,
    Administrative,
    BorderZone,
    Census,
    EmergencyOperationArea,
    Forest,
    ForestCompartment,
    Hazard,
    Health,
    Historic,
    LimitedTrafficZone,
    LocalAuthority,
    LowEmissionZone,
    Maritime,
    Marker,
    NationalPark,
    Place,
    Political,
    PostalCode,
    ProtectedArea,
    ReligiousAdministration,
    SpecialEconomicZone,
    Statistical,
    Disputed,
    Timezone,
    PublicTransport
}

#[feature_sub_type]
pub enum Building {
    // Accommodation
    Apartments,
    Barracks,
    Bungalow,
    Cabin,
    Detached,
    Annexe,
    Dormitory,
    Farm,
    Ger,
    Hotel,
    House,
    Houseboat,
    Residential,
    SemidetachedHouse,
    StaticCaravan,
    StillHouse,
    Terrace,
    TreeHouse,
    Trullo,
    // Commercial
    Commercial,
    Industrial,
    Kiosk,
    Office,
    Retail,
    Supermarket,
    Warehouse,
    // Religious
    Basilica,
    Cathedral,
    Chapel,
    Church,
    KngdomHall,
    Monastery,
    Mosque,
    Prebbytery,
    Religious,
    Shrine,
    Synagogue,
    Temple,
    // Civic/amenity
    Bakehouse,
    Bridge,
    Civic,
    ClockTower,
    College,
    FireStation,
    Government,
    Gatehouse,
    Hospital,
    Kindergarten,
    Museum,
    Public,
    School,
    Toilets,
    TrainStation,
    University,
    // Agricultural/plant production
    Barn,
    Conservatory,
    Cowshed,
    FarmAuxiliary,
    Greenhouse,
    SluryTank,
    Stable,
    Sty,
    Livestock,
    // Sports
    Grandstand,
    Pavilion,
    RidingHall,
    SportsHall,
    SportsCentre,
    Stadium,
    // Storage
    AllotmentHouse,
    Boathouse,
    Hangar,
    Hut,
    Shed,
    // Cars
    Carport,
    Garage,
    Garages,
    Parking,
    // Power/technical buildings
    Digester,
    Service,
    TechCab,
    TransformerTower,
    WaterTower,
    StorageTank,
    Silo,
    // Other buildings
    BeachHut,
    Bunker,
    Castle,
    Construction,
    Container,
    Guardhouse,
    Military,
    No, // TODO ???
    Outbuilding,
    Pagoda,
    QuonsetHut,
    Roof,
    Ruins,
    Ship,
    Tent,
    Tower,
    Transportation,
    TriumphalArch,
    Windmill,
    Yes
}

#[feature_sub_type]
pub enum Club {
    Aeronautical,
    Allotments,
    AmateurRadio,
    Anarchist,
    Art,
    Astornomy,
    Automobile,
    Aviation,
    Bicyle,
    Baduk,
    Birds,
    BoardGame,
    Cadet,
    Cannabis,
    CardGames,
    Charity,
    Chess,
    Cinema,
    Computer,
    Cooking,
    Culture,
    Dog,
    Doityourself,
    EnvironmentProtection,
    Equestrian,
    Ethnic,
    Fan,
    Filmmaking,
    Fishing,
    Freemasonry,
    Game,
    Gardening,
    Golf,
    Hackerspace,
    History,
    Hunting,
    Juggling,
    Linux,
    LocalFood,
    ModelRailway,
    Motorcycle,
    Music,
    Nature,
    Nudism,
    Photography,
    Politics,
    Religion,
    Sailing,
    Scout,
    ScubdaDiving,
    Smoke,
    Social,
    Sport,
    Student,
    SurfLifeSaving,
    Theatre,
    Tourism,
    Veterans,
    Woodworking,
    Youth,
    YouthMovement,
}

#[feature_sub_type]
pub enum Craft {
    AgriculturalEngines,
    Atelier,
    BagRepair,
    Bakery,
    BasketMaker,
    Beekeeper,
    Blacksmith,
    Boatbuilder,
    Bookbinder,
    Brewery,
    Builder,
    CabinetMaker,
    Candlemaker,
    CarPainter,
    Carpenter,
    CarpetCleaner,
    CarpetLayer,
    Caterer,
    ChimneySweepter,
    Cleaning,
    Clockmakter,
    ClothesMending,
    Confectionery,
    Cooper,
    DentalTechnician,
    Distilery,
    DoorConstruction,
    Dressmaker,
    Electrician,
    ElectronicsRepair,
    Elevator,
    Emborderer,
    Engraver,
    FenceMaker,
    Floorer,
    Gardener,
    Glassblower,
    Glaziery,
    Goldsmith,
    GrindingMill,
    Gunsmith,
    Handicraft,
    Hvac,
    Insulation,
    InteriorDecorator,
    InteriorWork,
    Jeweller,
    Joiner,
    KeyCutter,
    Laboratory,
    Lapidary,
    Leather,
    Locksmith,
    Luthier,
    MetalConstruction,
    Mint,
    MusicalInstrument,
    OilMill,
    Optician,
    OrganBuilder,
    Painter,
    Paperhanger,
    ParquetLayer,
    Paver,
    PestControl,
    Photographer,
    PhotographicLaboratory,
    Photovoltaic,
    PianoTuner,
    Plasterer,
    Plumber,
    Pottery,
    Printer,
    Printmaker,
    Restoration,
    Rigger,
    Roofer,
    Saddler,
    Sailmaker,
    Sawmill,
    Scaffolder,
    Sculptor,
    Shoemaker,
    Signmaker,
    StandBuilder,
    Stonemason,
    StoveFitter,
    SunProtection,
    Tailor,
    Tatami,
    Tiler,
    Tinsmith,
    Toolmaker,
    Tuner,
    Upholsterer,
    Watchmaker,
    WaterWellDrilling,
    Weaver,
    Welder,
    WindowConstruction,
    Winery,
}

#[feature_sub_type]
pub enum DepaturesBoard {
    Delay,
    No,
    Realtime,
    Timetable,
    Yes,
}

#[feature_sub_type]
pub enum Education {
    ArtSchool,
    Centre,
    College,
    CookingSchool,
    DancingSchool,
    DrivingSchool,
    FacultativeSchool,
    FlighSchool,
    Kindergaren,
    LanguageSchool,
    MusicSchool,
    PrepSchool,
    SailingSchool,
    School,
    SkiSchool,
    SurfSchool,
    TradeSchool,
    Training,
    University,
}

#[feature_sub_type]
pub enum Emergency {
    AmbulanceStation,
    AssemblyPoint,
    Defibrillator,
    DisasterResponse,
    FireHydrant,
    FireWaterPond,
    Lifeguard,
    Phone,
    Yes,
}

#[feature_sub_type]
pub enum Geological {
    ColumnarJointing,
    Cone,
    Dyke,
    Fault,
    Fold,
    GiantsKettle,
    GlacialErratic,
    Hoodoo,
    Inselberg,
    LimestonePavement,
    MeteorCrater,
    Monocline,
    Moraine,
    Outcrop,
    PalaeontologicalSite,
    Pingo,
    RockGlacier,
    Sinkhole,
    Tor,
    Unconformity,
    VolcanicCalderaRim,
    VolcanicLavaField,
    VolcanicVent,
}

#[feature_sub_type]
pub enum Healthcare {
    Lol
}

#[feature_sub_type]
pub enum Office {
    Accountant,
    AdvertisingAgency,
    Airline,
    Architect,
    Association,
    Company,
    EducationalInstitution,
    EmploymentAgency,
    EnergySupplier,
    EstateAgent,
    FinancialAdvisor,
    Government,
    Insurance,
    It,
    Lawyer,
    Notary,
    TaxAdvisor,
    Telecommuication,
    Telecommunication,
}

#[feature_sub_type]
pub enum Route {
    Bicycle,
    Boat,
    Bus,
    Detour,
    Ferry,
    Foot,
    Hiking,
    Power,
    Railway,
    Road,
    Tracks,
    Train,
    Waterway,
}

#[derive(Display, EnumIter, EnumString, PartialEq, Eq, Hash)]
#[strum(serialize_all = "snake_case")]
#[enum_dispatch(FeatureSubType)]
pub enum Feature {
    Advertising(Advertising),
    Aerialway(Aerialway),
    Aeroway(Aeroway),
    Amenity(Amenity),
    Barrier(Barrier),
    Boundary(Boundary),
    Building(Building),
    Club(Club),
    Craft(Craft),
    DepaturesBoard(DepaturesBoard),
    Education(Education),
    Emergency(Emergency),
    Geological(Geological),
    Healthcare(Healthcare),
    //Highway,
    //History,
    //Landcover,
    //Landuse,
    //Leisure,
    //#[strum(serialize = "man_made")]
    //ManMade,
    //Military,
    //Natural,
    Office(Office),
    //#[strum(serialize = "piste:type")]
    //PisteType,
    //Place,
    //Power,
    //#[strum(serialize = "public_transport")]
    //PublicTransport,
    //Railway,
    Route(Route),
    //Shop,
    //Telecom,
    //Tourism,
    //Waterway
}
